# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4125ff3d45a380d4453f63e61ad2c44366dc75a5f6cf7b116f968b1d73e0afec8ffeff58ccc440ba791df5ca56d51606dc2b96343f1c08949e5a5c8f5256c980

test:
  secret_key_base: 7f94df80f2c34d691a96f7445cf5254174ec83f87e700af9dde7ad2bc1cef9bd4e469b86e74756847f18c02d1d81aecb604b0f22d88706fa2a78333bd76cadf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
